/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {

//        Carro c = new Carro("Uno", 100);
//        c.acelerar(7665);
//        c.freiar(9000);
//        IO.println(c.toString());
//
//        Carro cc = new Carro("Palio");
//        IO.println(cc.toString());
//
//        Pessoa p = new Pessoa("Isak", "isak2000@gmail.com", "23424398870");
//        IO.println(p);

        Horario h = new Horario();
        h.setHorario(21, 43, 2);
        h.setHorario(21, 43, 500);
        IO.println(h);

        Horario m = new Horario();
        m.setHorario(21, 43);
        m.setHorario(21, 5000);
        IO.println(m);

        Horario s = new Horario();
        s.setHorario(21);
        s.setHorario(66);
        IO.println(s);
    }
}
