/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner entrada = new Scanner(System.in);

        while (entrada.hasNext()){
            String linha = entrada.nextLine();
            System.out.println(linha);
        }
    }
}
