/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Scanner;

public class App {
    public static void main(String[] args) {

        int[][] matriz = new int[9][9];
        int linhas = 0;

        Scanner entrada = new Scanner(System.in);
        while (entrada.hasNext()){

            String linha = entrada.nextLine();

            for (int i = 0; i < linha.length(); i++) {
                matriz[linhas][i] = linha.charAt(i) == '.' ? 0 : 9;
            }
            linhas++;
        }
    }
}
