/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        if (args.length == 2 || args.length == 3) {
            int e1 = Integer.parseInt(args[1]);
            int e2 = Integer.parseInt(args[2]);

            switch (args[0].toLowerCase()) {
                case "triangulo":

                    for (int i = 0; i <= e1; i++) {
                        System.out.println("*".repeat(i));
                    }
                    break;

                case "losango":
                    int elMetade = e1 / 2;
                    for (int i = 0; i < e1; i++) {

                        // Calcula espaços: diminui no topo, aumenta no fundo (módulo)
                        int espacos = Math.abs(elMetade - i);

                        // Calcula asteriscos: aumenta no topo, diminui no fundo (módulo)
                        int asteriscos = e1 - (2 * espacos);

                        // Imprime espaços
                        for (int j = 0; j < espacos; j++) {
                            System.out.print(" ");
                        }

                        // Imprime asteriscos
                        for (int j = 0; j < asteriscos; j++) {
                            System.out.print("*");
                        }
                        System.out.println();
                    }
                    break;

                case "retangulo":
                    for (int i = 0; i < e1; i++) {
                        for (int j = 0; j < e2; j++) {
                            if (i == 0 || i == e1 - 1 || j == 0 || j == e2 - 1) {
                                System.out.print("*");
                            } else {
                                System.out.print(" ");
                            }
                        }
                        System.out.println();
                    }
            }
        }
    }
}
