/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Horario horario = new Horario();

        horario.Horario(16, 33, 45);
        IO.println(horario.extenso());

        horario.Horario(22, 56, 00);
        IO.println(horario.extenso());

        horario.Horario(05, 01);
        IO.println(horario.extenso());
    }
}
