/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Horario horario = new Horario();
        horario.Horario(12, 33, 45);

        IO.println(horario.extenso());
    }
}
