/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Horario horario = new Horario();
        Horario horario2 = new Horario();

        horario.Horario(16, 03, 01);
        IO.println(horario.extenso());

        horario2.Horario(22, 56, 00);
        IO.println(horario.extenso());

        IO.println(horario.emSegundos());
        IO.println(horario2.emSegundos());

        IO.println(horario.diferenca(horario2));
    }
}
