/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;
import edu.princeton.cs.algs4.DrawListener;

import java.util.*;

public class App implements DrawListener {

    private Draw draw;
    private ArrayList<CartaGUI> baralho = new ArrayList<>();

    public App() {
        this.draw = new Draw();
        this.draw.setCanvasSize(1200,600);
        this.draw.setXscale(0, 1200);
        this.draw.setYscale(0, 600);
        this.draw.enableDoubleBuffering();
        this.draw.setDefaultCloseOperation(3);
        this.draw.setTitle("Jogo de cartas");

        this.draw.addListener(this);

        this.draw.clear(Draw.GREEN);
        this.draw.show();
        double x = 60;

        for (NaipeCarta naipe : NaipeCarta.values()){
            for (ValorCarta valor : ValorCarta.values()){
                CartaGUI carta = new CartaGUI(valor, naipe, false, x, 300);
                x += 21;
                baralho.add(carta);
            }
        }
        Collections.shuffle(baralho);
    }

    @Override
    public void mouseClicked(double x, double y) {
        for (CartaGUI c : baralho){
           if (c.clicouDentro(x, y)){
               c.virarCarta();
               c.desenhar(draw);
           }
        }
        draw.show();
    }

    public static void main(String[] args) {
        App app = new App();

        for (CartaGUI c : app.baralho){
            c.desenhar(app.draw);
        }
        app.draw.show();
    }
}