/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Motor motor = new Motor(65, 0, 4);
        Carro carro = new Carro("Fusca", motor);

        carro.acelerar(80);
    }
}
