/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Retangulo retangulo = new Retangulo(12, 12, "utf8");

        IO.println(retangulo);
    }
}