/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {

        Contador contador = new Contador();

        IO.println(contador.getValorAtual());
        contador.setValorAtual(455);
        IO.println(contador.getValorAtual());
        contador.incrementar();
        IO.println(contador.getValorAtual());
    }
}
