/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Ponto local = new Ponto(3.2, -68);

        local.setX(5);
        local.setY(11);
        IO.println(local); // IO.println(local.toString());
        IO.println((String.format("%.2f", local.distancia(new Ponto(6, 3)))));
    }
}
