/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Stack;

public class App {
    public static void main(String[] args) {
        String s = "-{[b x b - (4 x a x c)]/(2 x a)}";

        boolean balanceado = true;

        Stack<Character> pilha = new Stack<>();

        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);

            if (c == '(' || c == '[' || c == '{') {
                pilha.push(c);
            }

            else if (c == ')' || c == ']' || c == '}') {
                if (pilha.isEmpty()) {
                    balanceado = false;
                    break;
                }

                char topo = pilha.pop();

                if ((c == ')' && topo != '(') ||
                        (c == ']' && topo != '[') ||
                        (c == '}' && topo != '{')) {
                    balanceado = false;
                    break;
                }
            }
        }

        if (balanceado && pilha.isEmpty()) {
            System.out.println("Balanceado");
        } else {
            System.out.println("Não balanceado");
        }
    }
}
