/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import edu.princeton.cs.algs4.Draw;

import java.awt.*;
import java.util.concurrent.TimeUnit;

public class App {
    public static void main(String[] args) throws InterruptedException {
        Draw desenho = new Draw();
        desenho.setXscale(0, 1000);
        desenho.setYscale(0, 1000);

        desenho.enableDoubleBuffering();

        Color corDoRelogio = Color.GREEN;
        Relogio relogio = new Relogio(23, 59, 50, corDoRelogio, 100, 400, 1);

        while (true) {
            desenho.clear(Color.BLACK);
            relogio.desenhar(desenho, corDoRelogio);
            desenho.show();
            relogio.atualizarTempo();
            TimeUnit.SECONDS.sleep(1);
        }
    }
}