/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.ArrayDeque;
import java.util.Deque;

public class App {
    public static void main(String[] args) {
//        String sigla = IO.readln("Sigla: ");
//
//        int dia1 = Integer.parseInt(IO.readln("Dia 1: "));
//        DiasDaSemana d1 = DiasDaSemana.getByCodigo(dia1);
//
//        int dia2 = Integer.parseInt(IO.readln("Dia 2: "));
//        DiasDaSemana d2 = DiasDaSemana.getByCodigo(dia2);
//
//        DiasDaSemana[] dias = {d1, d2};
//        Disciplina d = new Disciplina(sigla, dias);
//        IO.println(d);

//        IO.println(Planetas.getByPosicao(2));
//        IO.println(Planetas.getByPosicao(6));
//

        Deque<Carta> baralho = new ArrayDeque<>();

        for(NaipeCarta n : NaipeCarta.values()){
            for (ValorCarta v : ValorCarta.values()){
                Carta carta = new Carta(v, n);
                baralho.add(carta);
            }
        }

        IO.println(baralho.toString());
    }
}
