/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Aviao aviao1 = new Aviao(10, 175, 575.000, 320.000, "helice", 4);
        Aviao aviao2 = new Aviao(10, 175, 575.000, 320.000, "fefefe", 4);
        Aviao aviao3 = new Aviao(10, 175, 575.000, 320.000, "helice", 200);

        IO.println(aviao1);
        IO.println(aviao2);
        IO.println(aviao3);
    }
}
