/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {
        Caixa<String> c = new Caixa<>("Olá mundo");
        Caixa<Pessoa> d = new Caixa<>(new Pessoa("Mateus"));

        String s = c.getConteudo();

        String err = d.getConteudo();
    }
}
