/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.InputMismatchException;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
//        Caixa<String> c = new Caixa<>("Olá mundo");
//        Caixa<Pessoa> d = new Caixa<>(new Pessoa("Mateus"));
//        String s = c.getConteudo();
//       String err = d.getConteudo();

        Scanner l = new Scanner(System.in);
        int a, b;

        try {
            System.out.println("Num 1 ");
            a = l.nextInt();

            System.out.println("Num 2 ");
            b = l.nextInt();

            int res = a/b;

            System.out.println(res);
        } catch (InputMismatchException e) {
            System.out.println("Tipo errado bocó");
            l.nextLine();
        } catch (ArithmeticException e){
            System.err.println(e);
            System.out.println("Vai dividir por zero aham");
            l.nextLine();
        }
        finally {
            System.out.println("Cabo");
        }
    }

}
