/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.Random;

public class App {
    public static void main(String[] args) {
        Random r = new Random();
        String[][] matriz = new String[9][9];

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                matriz[i][j] = ".";
            }
        }

        int sorte = 0;

        while (sorte <= 9) {
            int coluna = r.nextInt(9);
            int linha = r.nextInt(9);

            if (!matriz[linha][coluna].equals("*")) {
                matriz[linha][coluna] = "*";
                sorte++;
            }
        }

        for (int i = 0; i < 9; i++) {
            for (int j = 0; j < 9; j++) {
                System.out.print(matriz[i][j]);
                System.out.print(" ");
            }
            System.out.println();
        }
    }
}
