/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args) {

// Cria objeto com base na classe
//        Lampada l = new Lampada();
//
// Utiliza os métodos criados
//        System.out.println(l.isLigada());
//
//        l.setLigada();
//        System.out.println(l.isLigada());
//
// Cria segunda lâmpada (mesma classe, objetos separados)
//        Lampada l2 = new Lampada();
//        System.out.println(l2.isLigada());

        Caneta bic = new Caneta();
        bic.setCor("Vermelho");
        IO.println(bic.getCor());

        bic.setNivelTinta(55);
        IO.println(bic.getNivelTinta());

        bic.setFechada();
        IO.println(bic.desenhar(3, 5, 66, 55));
        IO.println(String.format("%.2f", bic.getNivelTinta()));
    }
}
