/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

public class App {
    public static void main(String[] args){
        Personagem personagens[] = new Personagem[3];

        personagens[0] = new Aldeao("Cleitin");
        personagens[1] = new Arqueiro("Rumberto");
        personagens[2] = new Cavaleiro("Junilson");

        for (Personagem p : personagens){
            IO.println(p.atacar());
            IO.println(p.mover(34, 90));
        }
    }
}
