/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {

    private final static HashMap<String, Livro> biblioteca = new HashMap<>();

    private static void cadastrar(){
        String isbn = IO.readln("ISBN: ");
        String titulo = IO.readln("TÍTULO: ");
        String autor = IO.readln("AUTOR: ");
        int ano = Math.abs(Integer.parseInt(IO.readln("ANO: ")));
        biblioteca.put(isbn, new Livro(isbn, titulo, autor, ano));
        System.out.println("Livro cadastrado com sucesso!");
    }

    private static void listar(){
        for (Livro livro : biblioteca.values()){
            System.out.println(livro);
        }
    }

    private static void consultarPorIsbn(){
        String isbn = IO.readln("ISBN: ");
        Livro l = biblioteca.get(isbn);
        if (l != null) System.out.println(l);
    }

    private void menu() {
        System.out.println("BIBLIOTECA");
        System.out.println("1. Cadastrar livro");
        System.out.println("2. Listar ISBN e título de todos os livros");
        System.out.println("3. Consultar livro por ISBN e imprimir todos os dados do livro");
        System.out.println("4. Consultar livro por autor e imprimir todos os dados do(s) livro(s)");
        System.out.println("5. Atualizar dados de um livro, exceto o ISBN");
        System.out.println("6. Remover um livro pelo ISBN");
        System.out.println("7. Sair");
        System.out.print("\nEscolha uma opção: ");
    }

    public static void main(String[] args) {
        App app = new App();
        int opcao;

        do {
            app.menu();
            opcao = Integer.parseInt(IO.readln());

            switch (opcao) {
                case 1:
                    cadastrar();
                    break;

                case 2:
                    listar();
                    break;

                case 3:
                    consultarPorIsbn();
                    break;

                case 4:
                    break;

                case 5:
                    String l = IO.readln("Digite o ISBN: ");
                    if (biblioteca.containsKey(l)) {

                    } else {
                        System.out.println("Livro não encontrado");
                    }
                    break;

                case 6:
                    String l = IO.readln("Digite o ISBN: ");
                    if (biblioteca.containsKey(l)) {
                        biblioteca.remove(l);
                    } else {
                        System.out.println("Livro não encontrado");
                    }
                    break;

                default:
                    System.out.println("Opção inválida!");
                    break;
            }

        } while (opcao != 7);
    }
}
