/*
 * This source file was generated by the Gradle 'init' task
 */
package engtelecom.poo;

import java.util.HashMap;

public class App {

    private final static HashMap<String, Livro> biblioteca = new HashMap<>();

    //1
    private static void cadastrar(){
        String isbn = IO.readln("ISBN: ");
        if (biblioteca.containsKey(isbn)) {
            System.out.println("Erro: Já existe um livro cadastrado com este ISBN!");
            return;
        }

        String titulo = IO.readln("TÍTULO: ");
        String autor = IO.readln("AUTOR: ");
        int ano = Math.abs(Integer.parseInt(IO.readln("ANO: ")));
        biblioteca.put(isbn, new Livro(isbn, titulo, autor, ano));
        System.out.println("Livro cadastrado com sucesso!");
    }

    //2
    private static void listar(){
        for (Livro livro : biblioteca.values()) {
            System.out.println(livro.getIsbn());
            System.out.println(livro.getTitulo());
        }
    }

    //3
    private static void consultarPorIsbn(){
        String isbn = IO.readln("ISBN: ");
        Livro l = biblioteca.get(isbn);
        if (l != null) System.out.println(l);
    }

    //4
    private static void consultarPorAutor() {
        String autor = IO.readln("Autor: ");
        boolean c = false;

        for (Livro l : biblioteca.values()) {
            if (l.getAutor().equalsIgnoreCase(autor)) System.out.println(l);
            c = true;
        }

        if (!c) {
            System.out.println("Nenhum livro encontrado.");
        }
    }

    //5
    private static void atualizar(){
        String isbn = IO.readln("ISBN: ");
        Livro l = biblioteca.get(isbn);

        if (l != null) {
            String titulo = IO.readln("TÍTULO: ");
            String autor = IO.readln("AUTOR: ");
            int ano = Math.abs(Integer.parseInt(IO.readln("ANO: ")));

            l.setAno(ano);
            l.setAutor(autor);
            l.setTitulo(titulo);
            System.out.println("Livro alterado com sucesso!");
        }
        else {
            System.out.println("Livro não encontrado.");
        }
    }

    //6
    private static void remover(){
        String isbn = IO.readln("ISBN: ");

        if (biblioteca.remove(isbn) != null) {
            System.out.println("Livro removido com sucesso!");
        } else {
            System.out.println("Livro não encontrado.");
        }
    }
    private void menu() {
        System.out.println("BIBLIOTECA");
        System.out.println("1. Cadastrar livro");
        System.out.println("2. Listar ISBN e título de todos os livros");
        System.out.println("3. Consultar livro por ISBN e imprimir todos os dados do livro");
        System.out.println("4. Consultar livro por autor e imprimir todos os dados do(s) livro(s)");
        System.out.println("5. Atualizar dados de um livro, exceto o ISBN");
        System.out.println("6. Remover um livro pelo ISBN");
        System.out.println("7. Sair");
        System.out.print("\nEscolha uma opção: ");
    }

    public static void main(String[] args) {
        App app = new App();
        int opcao;

        do {
            app.menu();
            opcao = Integer.parseInt(IO.readln());

            switch (opcao) {
                case 1 -> cadastrar();
                case 2 -> listar();
                case 3 -> consultarPorIsbn();
                case 4 -> consultarPorAutor();
                case 5 -> atualizar();
                case 6 -> remover();
                case 7 -> System.out.println("Encerrando");
                default -> System.out.println("Opção inválida!");
            }
        } while (opcao != 7);
    }
}
